#!/bin/bash
DIR=~/.i3

grep -E '^### The following was generated by vi3m\.sh ###$' $DIR/config >/dev/null
vi3m_conf=$?

[[ -f $DIR/preconfig ]]
vi3m_preconf=$?

grep -E '^\s*bindsym [^ ]+ mode' $DIR/preconfig
vi3m_modes=$?

#echo '0 = yes, 1 = no'
#echo "config has vi3m line? $vi3m_conf"
#echo "preconf exist? $vi3m_preconf"

if [[ $vi3m_modes == 0 ]]; then
cat << EOM
Something has gone wrong.
Your i3 config contains modes, which will cause vi3m normal mode to break. To
allow vi3m to work, comment out all the lines related to modes. Eventually I
might get around to adding proper handling or something, but until then, just
deal with it.
EOM
exit 1
fi

if [[ $vi3m_conf == 0 ]] && [[ $vi3m_preconf == 1 ]]; then
cat << EOM
Something has gone wrong.
Your i3 config has the vi3m generation line, but your preconfig does not exist.
To fix this, remove the vi3m-generated lines from your i3 config and try again.
EOM
[[ $TERM == dumb ]] && i3-nagbar -m 'There is an issue with your vi3m setup. Please run ~/.i3/vi3m/vi3m.sh to see why.'
exit 1
fi

if [[ $vi3m_conf == 1 ]] && [[ $vi3m_preconf == 0 ]]; then
cat << EOM
Something has gone wrong.
Your i3 config does not have the vi3m verification line, but your preconfig
exists. This script will absolutely never overwrite your i3 preconfig, so that
your i3 config data will never completely disappear. Chances are, you
accidentally did something to your i3 config to cause the vi3m verification to
disappear from it, and if so, moving the i3 config out of the i3 directory
and rerunning this script should fix the problem.
EOM
[[ $TERM == dumb ]] && i3-nagbar -m 'There is an issue with your vi3m setup. Please run ~/.i3/vi3m/vi3m.sh to see why.'
exit 1
fi

if [[ $vi3m_conf == 1 ]] && [[ $vi3m_preconf == 1 ]]; then
	cp $DIR/config $DIR/preconfig
fi

cp $DIR/config $DIR/config.bak
{
	# load preconfig
	cat $DIR/preconfig \
	| perl -pe 's#^(\s*bindsym [^ ]+) (reload|restart)$#\1 exec --no-startup-id ~/.i3/vi3m/vi3m.sh && i3-msg \2#'
	# load vi3m verification
	echo '### The following was generated by vi3m.sh ###'
	# load vi3m normal mode
	echo 'bindsym $mod+i mode "normal"'
	echo 'mode "normal" {'
	echo -e "\tbindsym i mode \"default\""
	cat $DIR/preconfig \
	| perl -pe 's/\\\n//' \
	| grep -E '^\s*bindsym \$mod\+' \
	| perl -pe 's/^(\s*)bindsym \$mod\+/\1bindsym /'
	echo '}'
	# load vi3m mappings
	$DIR/vi3m/generate_modes.py
} \
> $DIR/config || { # put this into the config, and if it breaks, restore the backup
	i3-nagbar -t error -m 'You have errors in your vi3m/config.py. Reverting to backup config.' &
	cp $DIR/config.bak $DIR/config
}
