#!/bin/bash
DIR=~/.i3

grep -E '^### The following was generated by vi3m\.sh ###$' $DIR/config >/dev/null
vi3m_conf=$?

[[ -f $DIR/preconfig ]]
vi3m_preconf=$?

#echo '0 = yes, 1 = no'
#echo "config has vi3m line? $vi3m_conf"
#echo "preconf exist? $vi3m_preconf"

if [[ $vi3m_conf == 0 ]] && [[ $vi3m_preconf == 1 ]]; then
cat << EOM
Something has gone wrong.
Your i3 config has the vi3m generation line, but your preconfig does not exist.
To fix this, remove the vi3m-generated lines from your i3 config and try again.
EOM
[[ $TERM == dumb ]] && i3-nagbar -m 'There is an issue with your vi3m setup. Please run ~/.i3/vi3m/vi3m.sh to see why.'
exit 1
fi

if [[ $vi3m_conf == 1 ]] && [[ $vi3m_preconf == 0 ]]; then
cat << EOM
Something has gone wrong.
Your i3 config does not have the vi3m verification line, but your preconfig
exists. This script will absolutely never overwrite your i3 preconfig, so that
your i3 config data will never completely disappear. As a result, you'll have
to look at your i3 config and preconfig and resolve the issue manually. Most
likely, if you move the preconfig out of your i3 directory, it should resolve.
EOM
[[ $TERM == dumb ]] && i3-nagbar -m 'There is an issue with your vi3m setup. Please run ~/.i3/vi3m/vi3m.sh to see why.'
exit 1
fi

if [[ $vi3m_conf == 1 ]] && [[ $vi3m_preconf == 1 ]]; then
	cp $DIR/config $DIR/preconfig
fi

cp $DIR/config $DIR/config.bak
{
	cat $DIR/preconfig \
	| perl -pe 's#^(\s*)bindsym ([^ ]+) (reload|restart)$#\1bindsym \2 exec --no-startup-id ~/.i3/vi3m/vi3m.sh && i3-msg \3#'
	$DIR/vi3m/generate_modes.py
} > $DIR/config || {
	i3-nagbar -t error -m 'You have errors in your vi3m/config.py. Reverting to backup config.' &
	cp $DIR/config.bak $DIR/config
}
